export const GamesOnGalery = [
  {
    id: 1,
    title: "Lorem ipsum",
    heading: "update",
    longTitle: "Praesent laoreet porta leo, mollis hendrerit 5 erat",
    thumbnail: "rocket.svg",
    coverimg: "cover1.jpg",
    link: "gameslist/download?id=1",
  },
  {
    id: 2,
    title: "Lorem ipsum",
    heading: "update",
    longTitle: "Praesent laoreet porta leo, mollis hendrerit 5 erat",
    thumbnail: "rocket.svg",
    coverimg: "cover2.jpg",
    link: "gameslist/download?id=2",
  },
  {
    id: 3,
    title: "Lorem ipsum",
    heading: "update",
    longTitle: "Praesent laoreet porta leo, mollis hendrerit 5 erat",
    thumbnail: "rocket.svg",
    coverimg: "cover3.jpg",
    link: "gameslist/download?id=3",
  },
  {
    id: 4,
    title: "Lorem ipsum",
    heading: "update",
    longTitle: "Praesent laoreet porta leo, mollis hendrerit 5 erat",
    thumbnail: "rocket.svg",
    coverimg: "cover4.jpg",
    link: "gameslist/download?id=4",
  },
  {
    id: 5,
    title: "Lorem ipsum",
    heading: "update",
    longTitle: "Praesent laoreet porta leo, mollis hendrerit 5 erat",
    thumbnail: "rocket.svg",
    coverimg: "cover5.jpg",
    link: "gameslist/download?id=5",
  },
  {
    id: 6,
    title: "Lorem ipsum",
    heading: "update",
    longTitle: "Praesent laoreet porta leo, mollis hendrerit 5 erat",
    thumbnail: "rocket.svg",
    coverimg: "cover5.jpg",
    link: "gameslist/download?id=6",
  },
];
